services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - bookstore_default
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./env.dev
    depends_on:
      - db
    networks:
      - bookstore_default

volumes:
  postgres_data:

networks:
  bookstore_default:
    driver: bridge
