name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    - name: Set DJANGO_ALLOWED_HOSTS environment variable
      run: echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV

    - name: Set SECRET_KEY environment variable
      run: echo "SECRET_KEY=SUA_CHAVE_SECRETA_AQUI" >> $GITHUB_ENV

    - name: Test
      run: |
        poetry run python manage.py test
