name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bookstore_dev_db
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Set DJANGO_SETTINGS_MODULE environment variable
      run: echo "DJANGO_SETTINGS_MODULE=bookstore.settings" >> $GITHUB_ENV

    - name: Set PostgreSQL environment variables
      run: |
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/bookstore_dev_db" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        poetry run python manage.py migrate

    - name: Run tests
      run: |
        poetry run pytest
